# Generated by Django 3.1.7 on 2021-02-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0003_auto_20210222_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_CustomUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='completed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by_CustomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
