# Generated by Django 3.1.7 on 2021-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0004_auto_20210222_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Dev', 'Dev'), ('Boss Man', 'Boss Man')], max_length=60, null=True),
        ),
    ]
